name = "StaticCompiler"
uuid = "81625895-6c0f-48fc-b932-11a18313743c"
authors = ["Tom Short"]
version = "0.4.2"

[deps]
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
CodeInfoTools = "bc773b8a-8374-437a-b9f2-0e9785855863"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
GPUCompiler = "0.13"
LLVM = "4.8"
julia = "1.7"
CodeInfoTools = "0.3"
MacroTools = "0.5"

[extras]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Formatting"]
