name = "StaticCompiler"
uuid = "81625895-6c0f-48fc-b932-11a18313743c"
authors = ["Tom Short and contributors"]
version = "0.4.12"

[deps]
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"
CodeInfoTools = "bc773b8a-8374-437a-b9f2-0e9785855863"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LLD_jll = "d55e3150-da41-5e91-b323-ecfd1eec6109"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticTools = "86c06d3c-3f03-46de-9781-57580aa96d0a"

[compat]
CodeInfoTools = "0.3"
GPUCompiler = "0.19"
LLVM = "5"
MacroTools = "0.5"
StaticTools = "0.8"
julia = "1.8, 1.9"

[extras]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Formatting"]
