name = "StaticCompiler"
uuid = "81625895-6c0f-48fc-b932-11a18313743c"
authors = ["Tom Short"]
version = "0.1.0"

[deps]
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
LLVM_full_jll = "a3ccf953-465e-511d-b87f-60a6490c289d"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.2"

[extras]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Formatting"]
